name: deploy to S3

on:
  push:
    branches: [main]

jobs:
  build:
    name: build and deploy to s3
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build
        env:
          NEXT_PUBLIC_GISCUS_REPO: Yumamama00/Yurutech-blog
          NEXT_PUBLIC_GISCUS_REPOSITORY_ID: R_kgDOHQOpNw
          NEXT_PUBLIC_GISCUS_CATEGORY: Comment
          NEXT_PUBLIC_GISCUS_CATEGORY_ID: DIC_kwDOHQOpN84CO2Bd
          GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_GTAG_ID }}

      - name: s3 sync
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-1'
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          SOURCE_DIR: 'out'

      - name: invalidate cloudfront
        uses: chetan/invalidate-cloudfront-action@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-1'
          DISTRIBUTION: ${{ secrets.AWS_CF_DISTRIBUTION }}
          PATHS: '/*'
